Grammar improvements
PaperMC/Hangar pull request #260
Opened 2020-12-14 05:02 UTC by kadenscott

Just a few tweaks to grammar, let me know if there's anything you'd like to change. Maybe keep this open if I find anything else, tomorrow (when I have some time) I'll take a deeper look.

2020-12-14 08:50 UTC, KennyTV requested changes

2020-12-14 08:50 UTC, KennyTV commented on src/main/frontend/src/assets/locales/en.json
> +        "info": "These are special words that will return your project when people add them to their searches. (max 5 keywords)"
```suggestion
        "info": "These are special words that will return your project when people add them to their searches (max 5 keywords)."
```

2020-12-14 08:50 UTC, KennyTV commented on src/main/frontend/src/assets/locales/en.json
> +        "info": "A short description of your project. (max 120 characters)"
```suggestion
        "info": "A short description of your project (max 120 characters)."
```

2020-12-14 08:50 UTC, KennyTV commented on src/main/frontend/src/assets/locales/en.json
> +        "info": "Should events (like new releases) have a forum post automatically created?"
```suggestion
        "info": "Should events like new releases have a forum post created automatically?"
```

2020-12-14 21:23 UTC, mdcfe commented on src/main/frontend/src/assets/locales/en.json
> +        "info": "Should events (like new releases) have a forum post automatically created?"
```suggestion
        "info": "Should events like new releases automatically create a forum post?"
```
@KennyTV Slightly different and reads better to me, not sure what others think though

2020-12-15 03:17 UTC, Machine-Maker commented
I’m not sure about this? You are changing the grammar in the frontend json file. We have identical localization in the hangar app resources folder “messages.properties”. Every so often, I’ve just been using a script I wrote to convert from .properties to .json. So at some point, we need better integration of those two systems. 


TLDR; make changes to messages in “message.properties” NOT the json since that will get generated automatically from messages.properties.

2020-12-17 02:55 UTC, kadenscott commented
Lol, sounds good. Sorry, still have yet to figure out how this project is structured. I'm gonna delete & re-fork and clone it so I can properly see what I'm doing. Will open a new PR in a few.

2020-12-17 02:55 UTC, closed without merging