refactored api.js to axios and removed jquery (#186)
PaperMC/Hangar pull request #312
Opened 2021-01-19 21:03 UTC by marc-maurer

This pullrequest removes jquery from API.js and replaced it with axios.
Issue #186

2021-01-19 22:00 UTC, Machine-Maker commented
This is just a syntax-type suggestion, but I know I always like to, in axios promises, instead of doing 
```javascript
axios.get().then((response) => {
    let data = response.data;
    //...
});
```
I like
```javascript
axios.get().then(({ data }) => {
    //...
});
```
idk if that's a bad practice or smth, feel free to correct me.

2021-01-20 19:47 UTC, marc-maurer commented
Done! Also found and fixed a bug that I accidentally introduced with my first change.

2021-01-20 21:58 UTC, MiniDigger commented on src/main/frontend/src/api.js
> +                        .post('/api/v1/authenticate', {}, { headers: { 'Content-Type': 'application/json' } })
Why does this not post against authenticate/user anymore?

2021-01-20 21:59 UTC, MiniDigger commented on src/main/frontend/src/api.js
> +                                console.log(data);
Muh debug logging spam

2021-01-20 21:59 UTC, MiniDigger commented on src/main/frontend/src/components/DependencySelection.vue
>                      });
Could prolly use a destructing pattern here too

2021-01-20 22:01 UTC, MiniDigger requested changes
Two minor things, else looks nice, thanks!

2021-01-21 10:40 UTC, merged